### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by tannerkrewson** [rameshvarun/netplayjs#23]
This looks awesome! Thanks for sharing!!

https://choosealicense.com/

**Comment by rameshvarun** [comment]
Everything under `netplayjs-client` is ISC licensed.

I will need to go over `netplayjs-demo` as I have copied some files from other MIT-licensed open-source projects. I will need to double check that those specific files are in fact under MIT license.

**Comment by rameshvarun** [comment]
- Verified that all the assets are distributed under permissive licenses
- Added attribution in README
- License repo under ISC
