### ISSUE TITLE
How deterministic is this game?

### ISSUE THREAD

**Issue by ValorZard** [rameshvarun/netplayjs#43]
Does this use Fixed Point numbers or soft floats to prevent desyncs?

**Comment by rameshvarun** [comment]
Ultimately that's up to you. Here's what NetplayJS assumes:
- NetplayJS does not require that your game code be deterministic.
- By default NetplayJS assumes non-determinism and uses [full state sync messages](https://github.com/rameshvarun/netplayjs/blob/8a37bddcc81db8c481884edbccfc49b3d999504a/netplayjs-client/src/netcode/rollback.ts#L99) to keep players in sync with the host.
- If you can guarantee that your game code is deterministic, you can set [`Game.deterministic = true`](https://github.com/rameshvarun/netplayjs/blob/8a37bddcc81db8c481884edbccfc49b3d999504a/netplayjs-client/src/game.ts#L31) which turns off state sync messages and improves network utilization.
- This flag is enabled in the [emulator](https://github.com/rameshvarun/netplayjs/blob/8a37bddcc81db8c481884edbccfc49b3d999504a/netplayjs-demo/src/examples/emulator.ts#L18) and [physics](https://github.com/rameshvarun/netplayjs/blob/8a37bddcc81db8c481884edbccfc49b3d999504a/netplayjs-demo/src/examples/physics.ts#L24) examples.

The next step is to ask what Javascript operations are deterministic and what operations are non-deterministic. Unfortunately it's a difficult question to answer, and I haven't seen a definitive exploration of this topic.
