### ISSUE TITLE
3+ players?

### ISSUE THREAD

**Issue by WofWca** [rameshvarun/netplayjs#82]
I just found this library and I'm struggling to figure out whether it's only suitable for two-player games. If 3+ player games are supported, it would be nice to showcase it on the demo page, e.g. with the "FPS" game, which, based on my tests, does not appear to function with three browser windows open.

**Comment by rameshvarun** [comment]
It's not supported yet #1.

**Comment by WofWca** [comment]
Duplicate of #1

Still, maybe it makes sense to state it in README for the time being.
